name: Tests & Coverage
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: []
        python-version: []
        include:
        - os: ubuntu-latest
          python-version: "3.7"
        - os: ubuntu-latest
          python-version: "3.8"
          codecov: true
        - os: ubuntu-latest
          python-version: "3.9"
        - os: ubuntu-latest
          python-version: "3.10"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          add-pip-as-python-dependency: true
          activate-environment: pydna_test_environment
          python-version: ${{ matrix.python-version }}
          environment-file: pydna_test_environment.yml
          use-only-tar-bz2: true

      - name: conda info
        shell: bash -l {0}
        run: conda info --all

      - name: conda list
        shell: bash -l {0}
        run: conda list